### PR TITLE
Fix obc state enum

### PR DESCRIPTION
**Pull request by Robert108**

### CODE REVIEW

**Comment by SebastianSvanland** [comment]
Hmm, shouldn't we start adding these things to the ROS messages? That way we ensure that e.g. OBC states enum will match in both backend and frontend and for all other python modules.

**Comment by SebastianSvanland** [comment]
@Robert108 Do you think it's a good idea? We should fix this bug asap

**Comment by Robert108** [comment]
@SebastianSvanland Yes that is a good idea! But it could be worth waiting with introducing enum definitions to when we rewrite OBC. I have a feeling we will do a overhaul of these messages then anyway.

**Review by SebastianSvanland — APPROVED** [review]
Sounds fair

**Pull request merged**
