### PR TITLE
Update network settings in compose file

### PR DESCRIPTION
**Pull request by Robert108**

### CODE REVIEW

**Comment by ceciliahernqvist** [comment]
This change gives me Failed TCP connection after Connect:
image

Same scenario/procedure works fine with ATOS dev branch.
I am not running Docker Desktop.

**Comment by Robert108** [comment]
@ceciliahernqvist Yepp, that is expect. When running with bridge mode you will need to specify you docker interface address (often called docker0 with an ip of 172.17.0.1 on the host) in the VehicleCatalog instead of the loop back address 127.0.0.1 which you can do when running in host mode.

**Comment by ceciliahernqvist** [comment]
Aa okay, makes sense then.

**Review by ceciliahernqvist — APPROVED** [review]

**Comment by Robert108** [comment]
@ceciliahernqvist I changed this some more and updated the documentation on using docker network. Now you don't need to know the IPs of the isoObject containers or the host IP, you just need to specify hostnames and they will be resolved automatically.

**Pull request merged**
