### PR TITLE
Add foxglove to compose, fix sercurity settings for GUI

### PR DESCRIPTION
**Pull request by Robert108**

### CODE REVIEW

**Review by samuelthoren — APPROVED** [review]
Why change from https?

**Review by victorjarlow — CHANGES_REQUESTED** [review]
The security argumentation needs to be present in the documentation.

**Review by SebastianSvanland — APPROVED** [review]
Security argumentation updated, I approve

**Review by SebastianSvanland — CHANGES_REQUESTED** [review]
Foxglove doesn't load foxglove extensions fully (some ports need to be reloaded for some reason)

**Review by SebastianSvanland — APPROVED** [review]
I think this can be merged and we'll handle the remaining issue in a new PR. I added the issue here: #627 so we don't forget

**Comment by SebastianSvanland** [comment]
The issue mentioned was solved in a commit.

@victorjarlow Are you satisfied with all the changes to approve this PR?

**Review by victorjarlow — APPROVED** [review]

**Pull request merged**
